class_name EncounterZone
extends Area2D
## Encounter zone: when the player steps inside, the energy barriers seal it and `waves` spawn one
## after another (each enemy warps in at a telegraphed spot away from the player). Clearing the last
## wave drops the barriers and emits `cleared` (the arena then opens the boss door).
##
## Wave format (one string per wave):  "chaser:4, shooter:2, tank:1"
##
## ENDLESS (`endless = true`): waves never run out. Each one is generated by endless_wave(): more
## enemies, tougher mixes and +hp_ramp HP / +damage_ramp damage per wave. Every boss wave is emitted
## with `total` 0 like any other wave; the arena adds the boss via reserve() + track().

signal started
signal wave_started(index: int, total: int)
signal wave_cleared(index: int, total: int)
signal cleared

const ENEMIES := {
	"chaser": preload("res://enemies/chaser.tscn"),
	"shooter": preload("res://enemies/shooter.tscn"),
	"tank": preload("res://enemies/heavy_tank.tscn"),
	"striker": preload("res://enemies/blade_striker.tscn"),
	"aegis": preload("res://enemies/aegis_guardian.tscn"),
	"lancer": preload("res://enemies/lancer.tscn"),
}

@export var waves: PackedStringArray = [
	"chaser:4",
	"chaser:3, shooter:2",
	"chaser:3, shooter:1, tank:2",
	"shooter:4, tank:2",
	"chaser:5, shooter:2, tank:2",
]
@export var zone_size := Vector2(1600, 900)
@export var hp_mult := 1.0
@export var damage_mult := 1.0
## Extra HP per wave (0.08 = +8% each wave).
@export var hp_ramp := 0.08
## From this wave on (1-based), random artillery shells rain on the player every few seconds.
@export var bombard_from_wave := 3
@export var bombard_interval := 5.0
@export var endless := false
## Extra enemy damage per wave (0.04 = +4% each wave, capped at MAX_DAMAGE_RAMP).
@export var damage_ramp := 0.0
## Endless: most enemies spawned in one wave (after that, waves only get tougher, not bigger).
const MAX_ENDLESS_ENEMIES := 22
const MAX_DAMAGE_RAMP := 2.5

var barriers: Array[Node] = []
var spawn_points: PackedVector2Array = []
var enemy_parent: Node
var wave := 0
var is_running := false
var is_cleared := false
var _alive: Array[Enemy] = []
var _pending := 0
var _bombard_t := 0.0
## Stall guard (see _check_stall).
const STALL_TIME := 20.0
const STALL_MAX_LEFT := 3
var _stall_t := 0.0


func _ready() -> void:
	collision_layer = 0
	collision_mask = 2
	monitorable = false
	var shape := CollisionShape2D.new()
	var box := RectangleShape2D.new()
	box.size = zone_size
	shape.shape = box
	add_child(shape)
	body_entered.connect(_on_body_entered)


func _on_body_entered(body: Node) -> void:
	if body is Mech and not is_running and not is_cleared:
		start()


func start() -> void:
	is_running = true
	for b in barriers:
		b.active = true
	started.emit()
	get_tree().create_timer(1.2, false).timeout.connect(_next_wave)


func alive_count() -> int:
	return _alive.size() + _pending


## Number of waves (0 = endless).
func total_waves() -> int:
	return 0 if endless else waves.size()


func is_boss_wave(n: int) -> bool:
	return endless and n > 0 and n % Game.ENDLESS_BOSS_EVERY == 0


## Enemy damage multiplier for the current wave.
func wave_damage_mult() -> float:
	return damage_mult * Game.diff("damage") * minf(1.0 + damage_ramp * (wave - 1), MAX_DAMAGE_RAMP)


## Endless wave `n`: grows by ~1.4 enemies a wave (capped); shooters join at wave 2, heavy tanks at 3,
## blade strikers at 4, lancers at 6, aegis guardians at 8 - and all of them get more common later.
## Boss waves bring a few escorts instead of a full wave.
func endless_wave(n: int) -> Array[String]:
	var count := mini(4 + int(n * 1.4), MAX_ENDLESS_ENEMIES)
	if is_boss_wave(n):
		count = mini(2 + n / Game.ENDLESS_BOSS_EVERY, 8)
	var kinds: Array = [["chaser", 1.0]]
	if n >= 2:
		kinds.append(["shooter", 0.7])
	if n >= 3:
		kinds.append(["tank", 0.15 + minf(n * 0.015, 0.25)])
	# Tougher robots join as the waves go on: Blade Strikers from 4, Lancers from 6, Aegis Guardians from 8.
	if n >= 4:
		kinds.append(["striker", 0.35 + minf(n * 0.01, 0.2)])
	if n >= 6:
		kinds.append(["lancer", 0.25 + minf(n * 0.01, 0.2)])
	if n >= 8:
		kinds.append(["aegis", 0.15 + minf(n * 0.008, 0.15)])
	var total := 0.0
	for k in kinds:
		total += k[1]
	var list: Array[String] = []
	for i in count:
		var r := randf() * total
		for k in kinds:
			r -= k[1]
			if r <= 0.0:
				list.append(k[0])
				break
	return list


func _next_wave() -> void:
	wave += 1
	wave_started.emit(wave, total_waves())
	var list: Array[String] = []
	if endless:
		list = endless_wave(wave)
	else:
		for part in waves[wave - 1].split(",", false):
			var kv := part.strip_edges().split(":")
			for i in (int(kv[1]) if kv.size() > 1 else 1):
				list.append(kv[0].strip_edges())
	list = _scale_for_difficulty(list)
	list.shuffle()
	_pending += list.size()
	for i in list.size():
		get_tree().create_timer(0.2 + i * 0.25, false).timeout.connect(_telegraph_spawn.bind(list[i]))


## Difficulty: more or fewer enemies per wave (Game.diff("count")). Removes random ones (keeping at least
## 2) or adds copies of random ones. Endless waves stay under a (modestly) raised cap.
func _scale_for_difficulty(list: Array[String]) -> Array[String]:
	var want := maxi(roundi(list.size() * Game.diff("count")), mini(2, list.size()))
	if endless:
		want = mini(want, roundi(MAX_ENDLESS_ENEMIES * minf(Game.diff("count"), 1.4)))
	var out := list.duplicate()
	out.shuffle()
	while out.size() > want:
		out.pop_back()
	while out.size() < want:
		out.append(list.pick_random())
	return out


## An enemy the arena will add to this wave later (e.g. a boss that drops in after a telegraph):
## the wave can't clear until it has been track()ed and killed.
func reserve() -> void:
	_pending += 1


## Adds an externally spawned enemy to the current wave (pair with reserve()).
func track(e: Enemy) -> void:
	_pending = maxi(_pending - 1, 0)
	e.died.connect(_on_enemy_died)
	_alive.append(e)


func _telegraph_spawn(kind: String) -> void:
	var pos := _pick_spawn_point()
	# Warp-in telegraph: a pulsing magenta ring for 0.7 s.
	for k in 3:
		get_tree().create_timer(k * 0.22, false).timeout.connect(func() -> void:
			Combat.shockwave(pos, 70.0 - k * 15.0, Color(1.0, 0.3, 0.8), 0.3))
	get_tree().create_timer(0.7, false).timeout.connect(_spawn.bind(kind, pos))


func _spawn(kind: String, pos: Vector2) -> void:
	_pending -= 1
	if not ENEMIES.has(kind):
		push_warning("Unknown enemy kind '%s'" % kind)
		_check_clear()
		return
	var e: Enemy = ENEMIES[kind].instantiate()
	e.position = pos
	e.max_hp *= hp_mult * (1.0 + hp_ramp * (wave - 1)) * Game.diff("hp")
	e.move_speed *= Game.diff("speed")
	e.damage_mult = wave_damage_mult()
	# Tank-type enemies: armor tier by wave - triple armor gets likelier the further in you are.
	if e is HeavyTank:
		e.armor_tier = 3 if randf() < triple_armor_chance() else 2
	e.died.connect(_on_enemy_died)
	_alive.append(e)
	(enemy_parent if enemy_parent else get_parent()).add_child(e)


func _pick_spawn_point() -> Vector2:
	var mech := get_tree().get_first_node_in_group("player") as Node2D
	var best := global_position
	for i in 20:
		var p := spawn_points[randi() % spawn_points.size()] if not spawn_points.is_empty() else \
			global_position + Vector2(randf_range(-0.4, 0.4) * zone_size.x, randf_range(-0.4, 0.4) * zone_size.y)
		best = p
		if mech == null or p.distance_to(mech.global_position) > 340.0:
			break
	return best


func _on_enemy_died(e: Enemy) -> void:
	_alive.erase(e)
	_stall_t = 0.0
	_check_clear()


## Stall guard: a wave down to its last few regular enemies with no kill for STALL_TIME seconds gets
## them warped back in near the player (with the normal warp-in telegraph), so however an enemy got
## stuck or lost (wedged in scenery, unreachable spot), a wave can never soft-lock the run.
func _check_stall(delta: float) -> void:
	if not is_running or _pending > 0 or _alive.is_empty() or _alive.size() > STALL_MAX_LEFT:
		_stall_t = 0.0
		return
	for e in _alive:
		if not is_instance_valid(e) or e.is_in_group("boss"):
			_stall_t = 0.0
			return
	_stall_t += delta
	if _stall_t < STALL_TIME:
		return
	_stall_t = 0.0
	var mech := get_tree().get_first_node_in_group("player") as Node2D
	for e in _alive:
		if not is_instance_valid(e) or e.dead:
			continue
		var pos := e.global_position
		if mech and not spawn_points.is_empty():
			var best := INF
			for i in 40:
				var p := spawn_points[randi() % spawn_points.size()]
				var d := p.distance_to(mech.global_position)
				var score := absf(d - 450.0)
				if d > 300.0 and score < best:
					best = score
					pos = p
		Combat.shockwave(e.global_position, 60.0, Color(1.0, 0.3, 0.8), 0.3)
		e.global_position = pos
		e.velocity = Vector2.ZERO
		for k in 3:
			get_tree().create_timer(k * 0.15, false).timeout.connect(func() -> void:
				Combat.shockwave(pos, 70.0 - k * 15.0, Color(1.0, 0.3, 0.8), 0.3))


func _check_clear() -> void:
	if not is_running or _pending > 0 or not _alive.is_empty():
		return
	Upgrades.vacuum()
	Game.record_wave_cleared()
	wave_cleared.emit(wave, total_waves())
	if endless:
		get_tree().create_timer(3.5 if is_boss_wave(wave) else 2.2, false).timeout.connect(_next_wave)
	elif wave >= waves.size():
		is_running = false
		is_cleared = true
		for b in barriers:
			b.active = false
		cleared.emit()
	else:
		get_tree().create_timer(2.2, false).timeout.connect(_next_wave)


func _physics_process(delta: float) -> void:
	_check_stall(delta)
	if not is_running or wave < bombard_from_wave:
		return
	_bombard_t -= delta
	if _bombard_t <= 0.0:
		_bombard_t = bombard_interval / Game.diff("bombard")
		var mech := get_tree().get_first_node_in_group("player") as Mech
		if mech and not mech.dead:
			for i in 3:
				var off := Vector2.ZERO if i == 0 else Vector2.from_angle(randf() * TAU) * randf_range(110, 220)
				Combat.artillery(mech.global_position + mech.velocity * 0.6 + off, 75.0, 14.0 * wave_damage_mult(), null, 1.0 + i * 0.25)


## Chance a tank rolls TRIPLE armor on the current wave (20% on wave 1, +12% per wave, max 80%).
func triple_armor_chance() -> float:
	return clampf(0.2 + 0.12 * (wave - 1), 0.2, 0.8)
